# Generated by Django 3.0.8 on 2020-12-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0006_auto_20201109_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tags',
            new_name='tags',
        ),
    ]
